root: none
gpu: 0
run_async: True
wait_after_process: 0.5 # in seconds

defaults:
  - model: detector

cam:
  id: 0
  width: 1280
  height: 720
  fps: 30
  flip_image: True
  temp_smoothing: False


assets_path:
  css: "assets/css"
  icons: "assets/icon"

css_styles:
  main: "main_style.css"

icon: "icon_dark_text.png"

logos: [

]
